module.exports.messages = [
  "#DOT buy setup @RoseSignalPremium",
  "Please don't put giga sell orders in my warriors.",
  "#BNB buy setup @RoseSignalPremium",
  "Deploying more capital, steady lads",
  "#LUNA buY setup @RoseSignalPremium",
  "as expected, market is in relief mode today. we are riding the winner LTC. Who cares the rest",
  "#XRP bUy setup @RoseSignalPremium",
  "I believe It can go higher before the halving but now It is time for consolidation again",
  "#ADA Buy setup @RoseSignalPremium",
  "which food are you looking for today ?",
  "#XRP buy setup @RoseSignalPremium",
  "#Germany Buy Setup",
  "#LINK buy setup @RoseSignalPremium",
  "#ETC close it for small profit",
  "Close #CVX too",
  "#DOT buy setup @RoseSignalPremium",
  "A bit concern but no need to rush",
  "#GRT buy setup @RoseSignalPremium",
  "While BTC ETH have not decided their moves, there might be few shitcoins signals next.",
  "#ETC buy setup @RoseSignalPremium",
  "Blackfriday?",
  "#LTC buy setup @RoseSignalPremium",
];
